#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "dumbdrop"
name = "DumbDrop"
description.en = "Dumb file dropper"
description.fr = "Transfert de fichier simple"

version = "1.0.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "GPL-3.0"
website = "https://www.dumbware.io/"
code = "https://github.com/DumbWareio/DumbDrop"
fund = "https://buymeacoffee.com/dumbware"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "200M"
ram.build = "200M"
ram.runtime = "70M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/dumbdrop"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.pin]
    ask.en = "Choose an optional PIN protection (4-10 digits)"
    ask.fr = "Choisissez la protection par code PIN en option (4 à 10 chiffres)"
    type = "number"
    default = ""

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DumbWareio/DumbDrop/archive/bf1c9a2dbdb051f34a8bea5f0b4082ca96888c7e.tar.gz"
    sha256 = "94a6181a0fd9e0435f0dc6baa132e7eeb951e0bb05268711923f49284a454afa"
    autoupdate.upstream = "https://github.com/DumbWareio/DumbDrop"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
